management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  application:
    name: Spring Timekeeper Application
    description: Spring application for timekeeping.
    version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timekeeper_spring
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true