management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  application:
    name: Spring Timekeeper Application
    description: Spring application for timekeeping.
    version: 1.0.0